sudo: required
language: generic
services:
    - docker
before_install:
    - docker build -t ausgeflippte/docker-prac -f dockerfile.dev .
script:
    - docker run -e CI=true ausgeflippte/docker-prac npm run test
